### ISSUE TITLE
Format of Contribution Log in Blog

### ISSUE THREAD

**Issue by ishana-goyal** [ossd-s23/shannonh800-weekly#1]
@shannonh800 I came across a small formatting issue in your blog. I think you've begun creating separate posts on your [blog](https://ossd-s23.github.io/shannonh800-weekly/) to track contributions, but I believe we are meant to track contributions on the [contributions.md file in your repository](https://github.com/ossd-s23/shannonh800-weekly/blob/gh-pages/contributions.md). 

Hope this helps!

**Comment by shannonh800** [comment]
I didn't even realize that--thanks! Fixed now.
